### ISSUE TITLE
Configure CI/CD

### ISSUE THREAD

**Issue by Danielwsx64** [brainn-co/xcribe#5]
Would be great have the CI/CD configured on CircleCI or maybe GitHub Actions.

**Comment by thiamsantos** [comment]
**TODO**:

- [ ] Add CI badge on README
- [ ] Configure auto-publish (CD)
- [ ] Add credo to CI

**Comment by thiamsantos** [comment]
We still miss from this issue:

- [ ] configure automatic push of the git tag in the CI
- [ ] Run the `Check version` step of the CI only on merge requests
- [ ] Only publish the package after all the tests passed in the master.
- [ ] Add credo to CI.
